name: Build Advanced Installer Project (.AIP) Clang Power Tools
on: [workflow_dispatch]
jobs:
  advinst-aip-build-demo:
    runs-on: windows-latest
    name: Build Aip Clang Power Tools
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Build AIP
        uses: caphyon/advinst-github-action@v1.0
        with:
          advinst-version: '19.2'
          advinst-license: ${{ secrets.ADVINST_LICENSE_KEY }}
          advinst-enable-automation: 'true'
          aip-path: ${{ github.workspace }}\ClangPowerTools.aip
          aip-build-name: DefaultBuild
          aip-package-name: ClangPowerToolsAI.vsix
          aip-output-dir:  ${{ github.workspace }}\GeneratedVsixWithGithubActions
      - name: Publish setup artifact
        uses: actions/upload-artifact@v2
        with:
          name: GeneratedVsixWithGithubActions
          path: ${{ github.workspace }}\GeneratedVsixWithGithubActions\ClangPowerToolsAI.vsix